services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - delivery-network

  auth-db:
    image: mysql:8.0
    container_name: auth-db
    restart: always
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - delivery-network

  order-db:
    image: mysql:8.0
    container_name: order-db
    restart: always
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - order_db_data:/var/lib/mysql
    networks:
      - delivery-network

  payment-db:
    image: mysql:8.0
    container_name: payment-db
    restart: always
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - payment_db_data:/var/lib/mysql
    networks:
      - delivery-network

  auth-service:
    build: ./auth
    container_name: auth-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - delivery-network

  order-service:
    build: ./order
    container_name: order-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
    networks:
      - delivery-network

  payment-service:
    build: ./payment
    container_name: payment-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
    networks:
      - delivery-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-service
      - order-service
      - payment-service
    networks:
      - delivery-network

networks:
  delivery-network:
    driver: bridge

volumes:
  rabbitmq_data:
  auth_db_data:
  order_db_data:
  payment_db_data:
