server:
  port: 8080
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "chave_grande_e_muito_segura_para_testes"
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: order-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**, /api/products/**, /api/product-types/**
        - id: payment-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/payments/**